# This is a utility file to test the mission-control docker image locally
# docker-compose --env-file=.env.docker-compose up

version: '3.9'
services:
  nginx:
    restart: always
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/templates
    ports:
      - '80:80'
  mission-control:
    env_file:
      - .env.docker-compose
    build:
      context: .
      args:
        PUBLIC_PATH: /modelujeme
